name: Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests on Linux
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test

      - name: Run Tests on non-Linux OS
        if: runner.os != 'Linux'
        run: npm test


